apiVersion: v1
kind: Service
metadata:
  name: trap-app-service
  labels:
    app: trap-app
spec:
  type: LoadBalancer
  selector:
    app: trap-app
  ports:
    - name: trap-app-port
      port: 8080
      protocol: TCP
      targetPort: trap-app-port